import type { FoodSeed } from './food-types';

/**
 * 粗粮类：莜面、豆面、玉米面及常见杂粮主食
 * 营养值为每 100g 熟重/可食部估算
 */
export const coarseGrainFoods: FoodSeed[] = [
  // —— 莜面（燕麦面，晋蒙特色）——
  {
    name: '莜面鱼鱼',
    category: '粗粮',
    aliases: ['莜面鱼儿', '莜面搓鱼', '搓鱼面', '莜面'],
    caloriesPer100g: 115,
    proteinPer100g: 5,
    carbsPer100g: 22,
    fatPer100g: 1.5,
    defaultServingG: 300,
    servingUnit: '碗',
  },
  {
    name: '莜面栲栳栳',
    category: '粗粮',
    aliases: ['栲栳栳', '莜面栳栳', '莜面卷', '山西莜面'],
    caloriesPer100g: 118,
    proteinPer100g: 5,
    carbsPer100g: 23,
    fatPer100g: 1.2,
    defaultServingG: 280,
    servingUnit: '份',
  },
  {
    name: '莜面窝窝',
    category: '粗粮',
    aliases: ['莜面窝头', '莜面蒸窝窝'],
    caloriesPer100g: 120,
    proteinPer100g: 5,
    carbsPer100g: 24,
    fatPer100g: 1,
    defaultServingG: 250,
    servingUnit: '份',
  },
  {
    name: '莜面饸饹',
    category: '粗粮',
    aliases: ['莜面河捞', '莜面饸络', '莜面条'],
    caloriesPer100g: 112,
    proteinPer100g: 5,
    carbsPer100g: 21,
    fatPer100g: 1.5,
    defaultServingG: 350,
    servingUnit: '碗',
  },
  {
    name: '莜面饺子',
    category: '粗粮',
    aliases: ['莜面蒸饺', '莜面水饺'],
    caloriesPer100g: 165,
    proteinPer100g: 6,
    carbsPer100g: 28,
    fatPer100g: 3,
    defaultServingG: 220,
    servingUnit: '份',
  },
  {
    name: '炒莜面',
    category: '粗粮',
    aliases: ['莜面炒面', '素炒莜面'],
    caloriesPer100g: 145,
    proteinPer100g: 5,
    carbsPer100g: 24,
    fatPer100g: 4,
    defaultServingG: 320,
    servingUnit: '份',
  },
  {
    name: '莜面糊',
    category: '粗粮',
    aliases: ['莜面糊糊', '莜面粥'],
    caloriesPer100g: 75,
    proteinPer100g: 3,
    carbsPer100g: 14,
    fatPer100g: 1,
    defaultServingG: 350,
    servingUnit: '碗',
  },

  // —— 豆面（杂豆/豌豆/绿豆面等）——
  {
    name: '豆面饸饹',
    category: '粗粮',
    aliases: ['豆面河捞', '豆面条', '杂豆面饸饹', '豆面'],
    caloriesPer100g: 125,
    proteinPer100g: 8,
    carbsPer100g: 22,
    fatPer100g: 1.5,
    defaultServingG: 350,
    servingUnit: '碗',
  },
  {
    name: '豆面窝头',
    category: '粗粮',
    aliases: ['豆面窝窝', '杂豆窝头'],
    caloriesPer100g: 195,
    proteinPer100g: 9,
    carbsPer100g: 35,
    fatPer100g: 2,
    defaultServingG: 120,
    servingUnit: '个',
  },
  {
    name: '豌豆面饸饹',
    category: '粗粮',
    aliases: ['豌豆面', '豌豆面条'],
    caloriesPer100g: 128,
    proteinPer100g: 9,
    carbsPer100g: 21,
    fatPer100g: 1.5,
    defaultServingG: 350,
    servingUnit: '碗',
  },
  {
    name: '绿豆面煎饼',
    category: '粗粮',
    aliases: ['绿豆面', '豆面煎饼'],
    caloriesPer100g: 210,
    proteinPer100g: 9,
    carbsPer100g: 32,
    fatPer100g: 6,
    defaultServingG: 150,
    servingUnit: '张',
  },
  {
    name: '豆面饺子',
    category: '粗粮',
    aliases: ['豆面蒸饺'],
    caloriesPer100g: 175,
    proteinPer100g: 9,
    carbsPer100g: 28,
    fatPer100g: 4,
    defaultServingG: 220,
    servingUnit: '份',
  },
  {
    name: '杂豆面汤',
    category: '粗粮',
    aliases: ['豆面糊', '豆面汤'],
    caloriesPer100g: 70,
    proteinPer100g: 4,
    carbsPer100g: 12,
    fatPer100g: 1,
    defaultServingG: 350,
    servingUnit: '碗',
  },

  // —— 玉米面 ——
  {
    name: '玉米面条',
    category: '粗粮',
    aliases: ['玉米面面条', '棒子面面条', '黄面'],
    caloriesPer100g: 110,
    proteinPer100g: 3,
    carbsPer100g: 23,
    fatPer100g: 1,
    defaultServingG: 350,
    servingUnit: '碗',
  },
  {
    name: '玉米面窝头',
    category: '粗粮',
    aliases: ['棒子面窝头', '玉米窝窝', '窝窝头'],
    caloriesPer100g: 205,
    proteinPer100g: 4,
    carbsPer100g: 42,
    fatPer100g: 2,
    defaultServingG: 100,
    servingUnit: '个',
  },
  {
    name: '玉米面饼',
    category: '粗粮',
    aliases: ['棒子面饼', '玉米饼', '贴饼子'],
    caloriesPer100g: 215,
    proteinPer100g: 4,
    carbsPer100g: 40,
    fatPer100g: 4,
    defaultServingG: 120,
    servingUnit: '张',
  },
  {
    name: '玉米面糊',
    category: '粗粮',
    aliases: ['棒子面糊', '玉米面粥', '棒子面粥'],
    caloriesPer100g: 68,
    proteinPer100g: 2,
    carbsPer100g: 14,
    fatPer100g: 0.8,
    defaultServingG: 350,
    servingUnit: '碗',
  },
  {
    name: '玉米面馒头',
    category: '粗粮',
    aliases: ['棒子面馒头', '玉米馒头'],
    caloriesPer100g: 218,
    proteinPer100g: 5,
    carbsPer100g: 44,
    fatPer100g: 1.5,
    defaultServingG: 100,
    servingUnit: '个',
  },
  {
    name: '煎玉米饼',
    category: '粗粮',
    aliases: ['香煎玉米饼', '玉米煎饼'],
    caloriesPer100g: 235,
    proteinPer100g: 4,
    carbsPer100g: 38,
    fatPer100g: 7,
    defaultServingG: 130,
    servingUnit: '张',
  },
  {
    name: '玉米面饺子',
    category: '粗粮',
    aliases: ['棒子面饺子', '玉米面蒸饺'],
    caloriesPer100g: 170,
    proteinPer100g: 5,
    carbsPer100g: 30,
    fatPer100g: 3,
    defaultServingG: 220,
    servingUnit: '份',
  },

  // —— 其它常见粗粮主食 ——
  {
    name: '荞麦面',
    category: '粗粮',
    aliases: ['荞麦饸饹', '荞面', '日式荞麦面'],
    caloriesPer100g: 105,
    proteinPer100g: 4,
    carbsPer100g: 21,
    fatPer100g: 0.8,
    defaultServingG: 350,
    servingUnit: '碗',
  },
  {
    name: '荞麦馒头',
    category: '粗粮',
    aliases: ['荞麦馍', '荞面馒头'],
    caloriesPer100g: 210,
    proteinPer100g: 7,
    carbsPer100g: 40,
    fatPer100g: 2,
    defaultServingG: 100,
    servingUnit: '个',
  },
  {
    name: '杂粮饭',
    category: '粗粮',
    aliases: ['五谷饭', '糙米饭', '二米饭', '藜麦饭'],
    caloriesPer100g: 125,
    proteinPer100g: 4,
    carbsPer100g: 26,
    fatPer100g: 1,
    defaultServingG: 200,
    servingUnit: '碗',
  },
  {
    name: '高粱面窝头',
    category: '粗粮',
    aliases: ['高粱窝头', '高粱面馍'],
    caloriesPer100g: 200,
    proteinPer100g: 5,
    carbsPer100g: 40,
    fatPer100g: 2,
    defaultServingG: 100,
    servingUnit: '个',
  },
  {
    name: '薏米粥',
    category: '粗粮',
    aliases: ['薏仁粥', '薏米红豆粥'],
    caloriesPer100g: 55,
    proteinPer100g: 2,
    carbsPer100g: 11,
    fatPer100g: 0.5,
    defaultServingG: 350,
    servingUnit: '碗',
  },
  {
    name: '黑米粥',
    category: '粗粮',
    aliases: ['黑米饭', '紫米粥'],
    caloriesPer100g: 72,
    proteinPer100g: 2.5,
    carbsPer100g: 15,
    fatPer100g: 0.6,
    defaultServingG: 350,
    servingUnit: '碗',
  },
  {
    name: '紫薯',
    category: '粗粮',
    aliases: ['蒸紫薯', '紫心地瓜'],
    caloriesPer100g: 82,
    proteinPer100g: 1.5,
    carbsPer100g: 20,
    fatPer100g: 0.2,
    defaultServingG: 180,
    servingUnit: '个',
  },
  {
    name: '杂粮煎饼',
    category: '粗粮',
    aliases: ['杂粮果子', '五谷煎饼'],
    caloriesPer100g: 230,
    proteinPer100g: 7,
    carbsPer100g: 36,
    fatPer100g: 7,
    defaultServingG: 180,
    servingUnit: '个',
  },
];
